name: Deploy to Public Plugin Repo

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Git identity
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Remove dev files
      run: |
        rm -rf src node_modules .gitignore package*.json webpack.config.js .github

    - name: Clone public repo
      run: |
        git clone https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/Ycaycepapa/roots-calendar.git deploy
        rsync -av --delete ./ ./deploy/
        cd deploy
        git add .
        git commit -m "Deploy from dev repo at $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push origin main
